// <auto-generated />
using System;
using Enquete.Infra.Data.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Enquete.Infra.Data.Migrations
{
    [DbContext(typeof(EnqueteContexto))]
    [Migration("20260329023005_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Enquete.Dominio.Entidades.Enquete", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Enquetes", (string)null);
                });

            modelBuilder.Entity("Enquete.Dominio.Entidades.Voto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EnqueteId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ParticipanteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("VotadoEm")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EnqueteId");

                    b.ToTable("Votos", (string)null);
                });

            modelBuilder.Entity("Enquete.Dominio.Entidades.Enquete", b =>
                {
                    b.OwnsMany("Enquete.Dominio.ValueObjects.OpcaoDeResposta", "Opcoes", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<Guid>("EnqueteId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)");

                            b1.HasKey("Id");

                            b1.HasIndex("EnqueteId");

                            b1.ToTable("EnqueteOpcoes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EnqueteId");
                        });

                    b.OwnsOne("Enquete.Dominio.ValueObjects.PrazoDeVotacao", "Prazo", b1 =>
                        {
                            b1.Property<Guid>("EnqueteId")
                                .HasColumnType("char(36)");

                            b1.Property<DateTime>("Fim")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("PrazoFim");

                            b1.Property<DateTime>("Inicio")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("PrazoInicio");

                            b1.HasKey("EnqueteId");

                            b1.ToTable("Enquetes");

                            b1.WithOwner()
                                .HasForeignKey("EnqueteId");
                        });

                    b.Navigation("Opcoes");

                    b.Navigation("Prazo")
                        .IsRequired();
                });

            modelBuilder.Entity("Enquete.Dominio.Entidades.Voto", b =>
                {
                    b.HasOne("Enquete.Dominio.Entidades.Enquete", null)
                        .WithMany("Votos")
                        .HasForeignKey("EnqueteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Enquete.Dominio.ValueObjects.OpcaoDeResposta", "Opcao", b1 =>
                        {
                            b1.Property<Guid>("VotoId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("OpcaoTexto");

                            b1.HasKey("VotoId");

                            b1.ToTable("Votos");

                            b1.WithOwner()
                                .HasForeignKey("VotoId");
                        });

                    b.Navigation("Opcao")
                        .IsRequired();
                });

            modelBuilder.Entity("Enquete.Dominio.Entidades.Enquete", b =>
                {
                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
